### ISSUE TITLE
ifort warnings

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#121]
We have lots of the following:

remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'

These happen because the compiler thinks we could *maybe* have some truncation on output statements.

For example, it is saying that d16.10 should be d17.10, and so on.

This would be easy to change, just it will change the format of output files (the fields will be 1 character larger in almost all cases, and some tools/tests might rely on the current field size, rather than chopping on white space.

**Comment by kyrsjo** [comment]
See also issue #120 , where this was a real problem. If we do this, we may have to update some canonicals. For fort.6 I'm not at all worried (i.e. I would just go ahead and change it), however there may be an issue with fort.10 etc.

Since this will change output (formatting), I would like this + updated canonicals to be done in its own pull request which also bumps version number.

**Comment by rdemaria** [comment]
No change in fort.10 format, please! The impact on tools is difficult to
assess.

**Comment by kyrsjo** [comment]
I found this one in a message from Eric McIntosh:

> P.S. In make_six I added the ifort option "-diag-disable remark"
> to 4 lines defining FCF for ifort, as in FCF=$FTZ......etc
> This gets rid of the annoying messages about formats.

**Comment by JamesMolson** [comment]
Fixed in #208
