### ISSUE TITLE
Evaluate use of git-lfs for SixTest?

### ISSUE THREAD

**Issue by Eothred** [SixTrack/SixTrack#158]
Noticed that the SixTest folder is now close to 1GB large. In particular the fma test seems to need a lot of disk space.

Maybe you already considered and rejected the idea, but you may consider to use [git-lfs](https://git-lfs.github.com/) to store the larger files. This is particularly relevant if the large files will be changing often, as each changeset will be available in the .git folder of each clone.

**Comment by rdemaria** [comment]
Perhaps we can try to reduce the size of tests first. For FMA it should be
possible, by keeping only the final results and not the intermediate files.
What do you all think?

**Comment by mfittere** [comment]
I would like to keep the intermediate files as then one can determine if there is a mistake in the normalization (in `sixtrack.s`) or in the tune caluclation (`plato*`) file. What we could do is to just track for fewer turns, e.g. 1024. This should reduce the file size by a factor 4.

**Comment by rdemaria** [comment]
Even 256 turns should be enough to prove the code is correct. What do you
think?

On 3 Jan 2017 17:17, "mfittere" <notifications@github.com> wrote:

I would like to keep the intermediate files as then one can determine if
there is a mistake in the normalization (in sixtrack.s) or in the tune
caluclation (plato*) file. What we could do is to just track for fewer
turns, e.g. 1024. This should reduce the file size by a factor 4.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SixTrack/SixTrack/issues/158#issuecomment-270152727>,
or mute the thread

**Comment by mfittere** [comment]
We would have to check that we get decent tunes with only 256.

**Comment by kyrsjo** [comment]
Another problematic set of files is the PDFs for manuals etc., compiled by LaTeX. Having them in the repository is nice because it makes it easy to link to the newest version of the manual, however they take space and they *always* cause merging issues. Maybe we should just publish the pdf on the webpage http://sixtrack.web.cern.ch/SixTrack/ ?

Furthermore, a big problem with files like the canonicals is that they are not really only committed once, they often needs to be regenerated and re-committed whenever we change something. Which will add up - possibly faster than storage and bandwidth increases. I'm not sure what happens to the early versions often found in branches before they are merged, but I would think they are included as well...

**Comment by mfittere** [comment]
For the FMA: I think we can reduce the tracking to 512 turns, which results in tune difference compared to the 4096 turns of 1.e-3 to 1.e-4. This reduces the folder size from 459M to 107 M. If this is not enought we can skip the dump files, but I would really like to keep them as the normalization is the tricky part and the dump files are checking exactly this part.

**Comment by kyrsjo** [comment]
Agreed that DUMP files should be kept. Let's reduce the number of turns the next time we need to update the FMA tests.

**Comment by mfittere** [comment]
I can do it with when we merge the wire. Now I have already checked 
everything and it shouldn't take too long.

**Comment by JamesMolson** [comment]
Moving the tests to their own repo and then adding it as a submodule would be nice too.
Trying to download a fresh release to make some small changes and having to pull down all the tests when you're on a bad connection isn't fun.

**Comment by vkbo** [comment]
This is solved with the HASH module for large files, and no longer an issue going forward. Of course, there isn't much we can do about all the massively large files in the repo history without doing a rewrite and therefore invalidate all forks.
