### ISSUE TITLE
Collimation block is not called for lattices without RF elements.

### ISSUE THREAD

**Issue by JamesMolson** [SixTrack/SixTrack#30]
If I try and enable the collimation code using lattices without RF cavities (for example, the current FCC-hh) then only thin4d is called.

thin6d contains the calls to enable the collimation tracking.

Putting RF elements into the lattice enables thin6d to be called and thus collimation works.
If collimation is enabled in fort.3 would it be possible to force thin6d to be used?

**Comment by kyrsjo** [comment]
Dear James, yes, I think a good solution would be to
* If collimation is on and trauthck was called, exit in error since the lattice is clearly wrong.
* In trauthin, always call thin6d if collimation is enabled. We may need to add some checking in case thin6dua was the one which "should" have been called and if so exit with an error.

We should also check that putting a crab cavity (which also contains longitudinal dynamics) triggers thin6d(ua).

**Comment by kyrsjo** [comment]
@JamesMolson Could you please test this version? It should be fixed there.
https://github.com/kyrsjo/SixTrack/commit/72ec7447840772faca1123e085a1ff5632ac11ea

@rbruce1 Do you see any problems with this fix? I.e. are there anything in collimat which is hardcoded to expect 15000 elements max? I don't have any testcase...

**Comment by JamesMolson** [comment]
That patch is the bignblz issue, and not the thin6d one?

**Comment by kyrsjo** [comment]
Fixed in https://github.com/kyrsjo/SixTrack/commit/649e823ac281aadc8ce6e4db4482124984573ece

**Comment by kyrsjo** [comment]
Thin4d and thick4d both include the block crabkick, which does change dpsv (delta P / P) etc.

That can't be right? @rdemaria

**Comment by rdemaria** [comment]
Well, you a get dipole...
