### ISSUE TITLE
Symplecticity check broken

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#398]
Simple fodo  + dipole kick+ RF cavity gives  large symplectic error

**Comment by tpersson** [comment]
Just some observations since:
1. This happens both for a horizonal and vertical kick.
2. Gets better at high energies.
3. Does not happen at 4D tracking.
4. The RF-voltage does not have an impact.
5. haronic number has no impact.
6. Changing the proton mass changes the results but only a little. 
7. The biggest error in my example is in the (6,2) element in the matrix but all 6, 1-4 were all rather big. This also of course depends on the kick strength.  

I also checked the RF-cavity and the kicks. It all looks fine to me. 

My guess at the moment is that it is the symplecticiy check itself that is faulty.

**Comment by JamesMolson** [comment]
Have you looked at the maps generated by the DA version?

**Comment by tpersson** [comment]
The maps look fine, at least the map for the RF-cavity and the correctors which are the ones which causes the problem in 6D.

**Comment by JamesMolson** [comment]
I mean it generates a one turn map to high order. How symplectic is it?

**Comment by tpersson** [comment]
Well that is the question... If you have an alternative way to check inside sixtrack I am very happy to try it.

**Comment by tpersson** [comment]
We also checked the dipedge test in sixtrack which with the quad precision version which gives ~10-30 something in symplecticity. However, I changed the IP2 element to a horizontal kicker and the symplecticity went down to 10-9, same results for a vertical kicker.

**Comment by rdemaria** [comment]
Fixed in dev #419
