### ISSUE TITLE
Different proton mass in the wire

### ISSUE THREAD

**Issue by tpersson** [SixTrack/SixTrack#443]
It looks to me like there are two proton masses. One called pma which is the input from the BEAM BLOC but there is also a pmpa which  looks some default value. In the WIRE map the pmpa is used (most other places pma is used. Is there a reason for this?

**Comment by rdemaria** [comment]
Even if there was a reason,  would it be possible to use only pma?

**Comment by tpersson** [comment]
As I see it we could use only pma, or rather the new nucm(j) which in the case of protons become pma.

**Comment by amereghe** [comment]
I guess that, if pma is used to compute the kick given to a particle, let's go with mucm(j). Otherwise, if pma is used to compute some parameters, the value of which is referenced to protons, then we should maybe set a more proper interface...

**Comment by JamesMolson** [comment]
I also push it into nucm(j)

There is also a value of the particle mass in the SYNC block.

It can also be set in the HION block, but if that does not exist I set it to default to whatever the default proton value is.

At some point I think there was a check if your set particle mass was within some tolerance of the default proton (or electron) value and if not, it would STOP.

**Comment by rdemaria** [comment]
I would keep the value of proton mass in the BEAM command of fort.3. That
is:
- replace any pmap with pma
- in daten copy the value of pma to mucm(j) and mucm0 if no HION is found
- never use pma/pmap and use always mucm(j) and mucm0

**Comment by tpersson** [comment]
Sure, I think that sounds reasonable.

There is a defined value in the common_modules.s90 and it is different depending on if fluka is used or not..


+if .not.fluka
  ! proton mass (MeV)
  real(kind=fPrec), parameter :: pmap = 938.271998_fPrec   !old
  ! real(kind=fPrec), parameter :: pmap = 938.2720813_fPrec  !2017

  ! electron mass (MeV) from PDG, 2002
  real(kind=fPrec), parameter :: pmae = 0.510998902_fPrec   !old
  ! real(kind=fPrec), parameter :: pmae = 0.5109989461_fPrec  !2017
+ei
+if fluka
!     A.Mereghetti and D.Sinuela Pastor, for the FLUKA Team
!     last modified: 08-12-2014
!     synch masses of proton and electron to values used by FLUKA
!     inserted in main code by the 'fluka' compilation flag
!     real(kind=fPrec), parameter :: pmap = 0.938272046e3_fPrec ! PDG 2014, Fluka-2011-dev
      real(kind=fPrec), parameter :: pmap = 0.938272310e3_fPrec ! PDG 20xx, Fluka-2011-pro
      real(kind=fPrec), parameter :: pmae = 0.510998928_fPrec   ! PDG 2014, Fluka-2011-dev
+ei
________________________________

**Comment by JamesMolson** [comment]
it is all in mod_fluka

**Comment by amereghe** [comment]
The characteristics of the synch particle are sent to Fluka via the FlukaIO at initialisation and after call to adia/adib in case of ramp. One of the reasons is to check that the masses of all tracked ion species are consistent between SixTrack and Fluka - for having the scattering and the tracking consistent. Then, depending if you are using the dev or pro version of Fluka, the actual value is different, but soon I guess we will remain with the pro version only... Units are in GeV/c2

What if the SYNC block is not present?

**Comment by rdemaria** [comment]
In "principle", if SYNC is not present, we should be doing 4D tracking and the mass value should not enter in the tracking calculations, which is the reason why I believe pma was put in SYNC.

**Comment by amereghe** [comment]
mm but then if you enter any scattering engine, I guess that you have to make assumption on which value of proton mass to take... moreover, I was implementing in the ELENs module the calculation of the kick to the reference particle... what about the wire?

**Comment by rdemaria** [comment]
For the scattering engine, is it practical to have all the constants used by a scattering engine in the input file?

For the elens and wire, we probably have a problem since we don't define the strengths in normalized quantities but in [A]. We could redefine the strengths in some [mrad m], but it is a bit ugly, or enforce a SYNC block for 4D tracking anyway...

**Comment by amereghe** [comment]
in general no, it is not practical - but in the end, the pdg regularly updates the mass of the proton, and there might be the need to keep it old or move to the very latest one... Or, as for the fluka coupling, if you use Fluka dev or pro you have to change it... I don't have a strong preference on where the user can state / update the value, but we should have a relatively easy way to do so.

For elens/wire, I agree with you. In this devel stage of these techniques/devices, for sure it is way easier for the sixtrack user to think in [A] rather than in normalised kicks... Maybe the enforcing of the 4D SYNC block could have 0 RF voltage...

**Comment by rdemaria** [comment]
For the time being, I would leave pma initialized to "a proton mass" (I would use the latest) and let SYNC update it. Then use nucm(j) and nucm0 everywhere. In case of 4D, the few people will have to cope with an hardcoded mass or free to use ion tracking to specify it exactly to what they want. This should not break backward compatibility, because the ion tracking input is new. (Actually, is there any documentation for the ions?)

If you think of any issue (real or potential) let's organize a meeting to discuss in person and take a decision.

**Comment by tpersson** [comment]
The PR #447 also fixes this issue
