### ISSUE TITLE
Energy update buggy in at least beambeam 6d element

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#655]
`dpsv1` was not updated in `include/beam6d.f90`. Other variables are missing and other elements might have the same type of issue.

**Comment by rdemaria** [comment]
After #766 , I think the option new delta should either disabled or changed such that one follows the sequence delta -> energy -> delta ....

**Comment by tpersson** [comment]
It looks to me that we can use the case: a new delta (3) with angles false (they are already updated).

@rdemaria Do you think we gain something by going re-calculate the delta again from the energy? It is not obvious to me...

**Comment by rdemaria** [comment]
The gain in delta -> energy -> delta is to make sure, in case we restart a simulation, that we can calculate delta from energy in a deterministic way. The problem is that it is possible that in the passage delta -> energy -> delta the value of delta changes. Therefore either we always keep track of energy and delta separately, also in the saved files, (which is not a bad idea in itself) or we always make sure that when one variable (energy) is updated the other one (delta) is updated from the first (energy).

**Comment by vkbo** [comment]
> After #766 , I think the option new delta should either disabled or changed such that one follows the sequence delta -> energy -> delta ....

The routine will no longer allow updates from anything other that energy after tracking has started.

**Comment by vkbo** [comment]
Just had a discussion with @tpersson about this. I think a good temporary solution is to allow the energy update routine to run from a changed delta array again also during tracking so that it can be used by beam-beam as well. This means we can remove the local update of arrays from the include file. It doesn't solve the delta > energy > delta problem, but it at least cleans up the code and prevents mistakes and inconsistencies in the updates of other energy-related arrays.

**Comment by rdemaria** [comment]
there is also the trombone matrix that needs this change....

**Comment by tpersson** [comment]
So the beam-beam was updating almost all the energy variables (not the thick ones) but this didn't cause any issues with the tests. However, quite a few tests need to be updated because:
dpsv(1:napx)*e0f)+e0f and dpsv(1:napx)+one))*e0f are not numerically the same.. The first one was used in the beam-beam element and the second in the updateEnergy

and I can not change it because the routine is used for other things so would also cause problems...So we update all the canonicals?

**Comment by rdemaria** [comment]
I think we need to update all the canonicals. I suspect
dpsv(1:napx)+one))*e0f is slightly better then the other one (more stable
for very small number).

**Comment by vkbo** [comment]
We had a look at the tests, and the canonicals are small it seems. So We'll just update them.
