### ISSUE TITLE
Unprotected do-loops (can become infinite) in DYNK

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#857]
When reading FUN FILE and the linear functions file in DYNK, there is no protection from infinite loops.

See the comments on #855 for line numbers and info.

**Comment by vkbo** [comment]
I had a look at this, and I'm not seeing how these loops can become infinite. There is an exit statement on the first occurrence of iostat /= 0 in all these loops.

**Comment by vkbo** [comment]
Closing this since all the loops have an exit on iostat /= 0. Which is no different than all the file readers using goto labels as loops with an exit goto on iostat or eof/err.

The only way these can become infinite is if the file is infinite, or a file system error causes a file to appear infinite. In that case, all file reading loops depending on eof will fail, which is a lot of them.
